[workspace]
git_release_enable = false
# Use `cargo-unc` crate CHANGELOG as top-level one
changelog_update = false

[[package]]
name = "cargo-unc"
changelog_update = true
changelog_path = "./CHANGELOG.md"
